import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Product Details',
    description: 'Generated by Product Details',
}

export default function ProductDetailLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
            <h2>Featured Products</h2>
        </>
    )
}
